### ISSUE TITLE
Exclude EOL odd versions from rebuilds

### ISSUE THREAD

**Issue by rarkins** [renovatebot/docker-node#136]
I don't think we need to build node 13 or 15 anymore (12, 14, 16, 17 is ok).

Any easy way to do it without listing every single 13 & 15 release in excludes?

**Comment by viceice** [comment]
Sure, but needs a builder tool extension to allow  ranges

**Comment by viceice** [comment]
- https://github.com/renovatebot/internal-tools/pull/289
