### ISSUE TITLE
move latest to v14

### ISSUE THREAD

**Issue by viceice** [renovatebot/docker-node#57]
As v14 is lts now, we should move `latest` docker tag to that.

**Comment by rarkins** [comment]
We probably need changes to renovate first. Otherwise users will get npm7 lock files

**Comment by viceice** [comment]
No, npm v7 comes with Mode v15 not v14 😉

**Comment by rarkins** [comment]
haha whoops

**Comment by viceice** [comment]
just verified 🙃 
![image](https://user-images.githubusercontent.com/1798109/97741018-671fcb00-1ae2-11eb-88e8-1fc5fa20e079.png)

node v14 comes with npm v6 and node v15 comes with npm v7
